/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.C_RecuperarContraseña;
import Modelo.M_RecuperarContraseña;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cruz
 */
public class RecuperarContraseña extends javax.swing.JFrame {

    M_RecuperarContraseña c = new M_RecuperarContraseña();
    C_RecuperarContraseña rc = new C_RecuperarContraseña();
    DefaultTableModel modeloTabla;
    
    public RecuperarContraseña() {
        initComponents();
        setLocationRelativeTo(null);
        validarCorreos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        tabla = new javax.swing.JScrollPane();
        tablaCorreos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Correo :");

        tablaCorreos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.setViewportView(tablaCorreos);

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(txtCorreo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Porfavor escriba un correo");
        }else{
        String d = txtCorreo.getText();
        boolean dato = false;
        for (int i = 0; i < tablaCorreos.getRowCount(); i++) {
        if(tablaCorreos.getValueAt(i, 0).equals(d)){
           dato = true;
        }
        
        }
      
        if(dato==true){
        Random r = new Random();
                
        c.setAdmin("desarrollosafety@gmail.com");
        c.setConAdmin("sjoqyiaebqtajymc");
        
        String letras = "aAbBcCdDeEfFgGhHiIjJkKlLmMnNñÑoOpPqQrRsStTuUvVwWxXyYzZ123456789";
        
        StringBuilder generador = new StringBuilder();
        char[] arreglo = letras.toCharArray();
        for(int i = 0;i<7;i++){
            generador.append(arreglo[r.nextInt(arreglo.length)]);
            
        }
        c.setContraseña(generador);
        c.setDestinatario(txtCorreo.getText());
        
        if(rc.actualizarContraJefe(c)){
            if(rc.RecuperarContraseña(c)){
            JOptionPane.showMessageDialog(null, "Correo enviado");
        }else{
            JOptionPane.showMessageDialog(null, "Error al enviar correo");
        }
        }else if(rc.actualizarContraAdmin(c)){
            if(rc.RecuperarContraseña(c)){
            JOptionPane.showMessageDialog(null, "Correo enviado");
        }else{
            JOptionPane.showMessageDialog(null, "Error al enviar correo");
        }
        }else if(rc.actualizarContraEmp(c)){
            if(rc.RecuperarContraseña(c)){
            JOptionPane.showMessageDialog(null, "Correo enviado");
        }else{
            JOptionPane.showMessageDialog(null, "Error al enviar correo");
        }
        }else if(rc.actualizarContraGerente(c)){
            if(rc.RecuperarContraseña(c)){
            JOptionPane.showMessageDialog(null, "Correo enviado");
        }else{
            JOptionPane.showMessageDialog(null, "Error al enviar correo");
        }
        }else{
            JOptionPane.showMessageDialog(null, "Error al enviar correo");
        }
        }
        else{
            JOptionPane.showMessageDialog(null, "Correo Invalido");
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperarContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane tabla;
    private javax.swing.JTable tablaCorreos;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables

        public void validarCorreos(){
        modeloTabla=rc.MostrarCorreos();
        tablaCorreos.setModel(modeloTabla);
    }

}
